### ISSUE TITLE
Create react app with home page for first commit to front-end repo

### ISSUE THREAD

**Issue by TheZukab** [Team9-DIN21AWAP/AWAP-front-end#3]

**Comment by Rexol** [comment]
Moved back to to-do since nothing changed in repo


![Image](https://user-images.githubusercontent.com/44599308/199719972-c5c0922b-95dd-4875-9708-f0a5de4454cf.png)

**Comment by TheZukab** [comment]
We are done with the static page of the website. Just finishing touches and we are pushing it to the repo
